// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmpyiaqurgmbqiqkcljv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tcHlpYXF1cmdtYnFpcWtjbGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMjY3NDUsImV4cCI6MjA3MTYwMjc0NX0.uRVCpdTj0CcxHqKOl7dEMgyr6NuRyZq9xOyM5Z_XzYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});